import { useEffect, useMemo, useState } from 'react'
import type { LocalServer } from '@shared/types'
import { useToast } from '../../toast'
import { IconSearch, IconServer, IconSliders } from '../../icons'
import Select from '../Select'
import { PALWORLD_SETTING_HINTS } from './palworldHints'

/** Keys already covered by the essentials card up top. */
const ESSENTIAL_KEYS = new Set([
  'ServerName',
  'ServerDescription',
  'ServerPassword',
  'ServerPlayerMaxNum',
  'ExpRate',
  'PalCaptureRate',
  'DayTimeSpeedRate',
  'NightTimeSpeedRate',
  'DeathPenalty'
])

/** Managed by the launcher — editing these would fight the pinning done at every start. */
const LOCKED_KEYS: Record<string, string> = {
  AdminPassword: 'generated by ELauncher; used for the management API',
  RESTAPIEnabled: 'pinned on — ELauncher manages the server through it',
  RESTAPIPort: 'pinned to the game port + 1',
  PublicIP: 'set automatically when the community listing is on'
}

const ENUM_OPTIONS: Record<string, { value: string; label: string }[]> = {
  Difficulty: ['None', 'Casual', 'Normal', 'Hard'].map((v) => ({ value: v, label: v })),
  DeathPenalty: [
    { value: 'None', label: 'None — keep everything' },
    { value: 'Item', label: 'Drop items' },
    { value: 'ItemAndEquipment', label: 'Drop items and equipment' },
    { value: 'All', label: 'Drop everything, including Pals' }
  ],
  RandomizerType: ['None', 'Region', 'All'].map((v) => ({ value: v, label: v })),
  LogFormatType: ['Text', 'Json'].map((v) => ({ value: v, label: v }))
}

const CROSSPLAY_PLATFORMS = ['Steam', 'Xbox', 'PS5', 'Mac']

/** First matching group wins; anything unmatched lands in "Other". */
const GROUPS: { title: string; match: RegExp }[] = [
  { title: 'Pals', match: /^Pal|Egg/ },
  { title: 'Players & combat', match: /Player|Damage|Stamina|Stomach|HpRegene|HPRegene|AimAssist|PvP|Invader|FriendlyFire|UNKO|Hardcore|Respawn|EnhanceStat/i },
  { title: 'Items & drops', match: /Item|Drop|Collection|Supply/i },
  { title: 'Base camps & guilds', match: /BaseCamp|Guild|BuildObject/i },
  { title: 'World & time', match: /Time|Randomizer|Difficulty|WorkSpeed|Rate/i },
  { title: 'Multiplayer & access', match: /Coop|Multiplay|LoginPenalty|FastTravel|StartLocation|Logout|Chat|ClientMod/i },
  { title: 'Saves & maintenance', match: /Save|Backup|Log|AutoReset|AliveMaxHours/i },
  { title: 'Network & platform', match: /Port|RCON|REST|Crossplay|Region|Auth|Ban|Lobby|IP$/i }
]

/** Splitting camelCase mangles acronyms ("PvP" -> "Pv P") — put the known ones back together. */
const ACRONYM_FIXES: [RegExp, string][] = [
  [/\bPv P\b/g, 'PvP'],
  [/\bU Id\b/g, 'UID'],
  [/\bHp\b/g, 'HP'],
  [/\bUi\b/g, 'UI']
]

/** "bEnableInvaderEnemy" -> "Enable Invader Enemy", "PalSpawnNumRate" -> "Pal Spawn Num Rate" */
function labelFor(key: string): string {
  let label = key
    .replace(/^b(?=[A-Z])/, '')
    .replace(/_/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .trim()
  for (const [pattern, fix] of ACRONYM_FIXES) label = label.replace(pattern, fix)
  return label
}

function groupOf(key: string): string {
  for (const g of GROUPS) if (g.match.test(key)) return g.title
  return 'Other'
}

const isBool = (v: string): boolean => /^(True|False)$/i.test(v)
const isNumeric = (v: string): boolean => /^-?\d+(\.\d+)?$/.test(v)

/** "1.000000" -> "1", "2.500000" -> "2.5" — the engine accepts both back. */
const trimFloat = (v: string): string => {
  const n = Number(v)
  return Number.isFinite(n) ? String(n) : v
}

/** Multiplier editor: quick ×presets plus a custom value. 1 is the game's normal. */
function RateEditor({ value, onChange }: { value: string; onChange: (v: string) => void }): React.JSX.Element {
  const current = Number(value)
  return (
    <div className="row" style={{ gap: 6, flexWrap: 'wrap' }}>
      <div className="segmented">
        {[0.5, 1, 2, 3].map((p) => (
          <button key={p} className={Math.abs(current - p) < 0.0001 ? 'active' : ''} onClick={() => onChange(String(p))}>
            ×{p}
          </button>
        ))}
      </div>
      <input
        type="number"
        step={0.1}
        min={0}
        style={{ width: 84 }}
        value={trimFloat(value)}
        onChange={(e) => onChange(e.target.value)}
      />
    </div>
  )
}

/** One-click bundles for the settings people actually tune. Everything stays editable before saving. */
const SERVER_PRESETS: { id: string; label: string; blurb: string; values: Record<string, string> }[] = [
  {
    id: 'relaxed',
    label: 'Relaxed',
    blurb: 'Chill co-op — faster XP and catches, generous drops, quick eggs, no death penalty, no base decay.',
    values: {
      ExpRate: '2',
      PalCaptureRate: '1.5',
      CollectionDropRate: '2',
      EnemyDropItemRate: '2',
      PlayerStomachDecreaceRate: '0.7',
      PalStomachDecreaceRate: '0.7',
      PlayerDamageRateDefense: '0.7',
      PalEggDefaultHatchingTime: '24',
      BuildObjectDeteriorationDamageRate: '0',
      DeathPenalty: 'None'
    }
  },
  {
    id: 'default',
    label: 'Default',
    blurb: "Pocketpair's standard balance — how the game ships.",
    values: {
      ExpRate: '1',
      PalCaptureRate: '1',
      CollectionDropRate: '1',
      EnemyDropItemRate: '1',
      PlayerStomachDecreaceRate: '1',
      PalStomachDecreaceRate: '1',
      PlayerDamageRateDefense: '1',
      PalEggDefaultHatchingTime: '72',
      BuildObjectDeteriorationDamageRate: '1',
      DeathPenalty: 'All'
    }
  },
  {
    id: 'challenge',
    label: 'Challenge',
    blurb: 'Slower progression, hungrier survival, tougher fights, full death penalty.',
    values: {
      ExpRate: '0.7',
      PalCaptureRate: '0.8',
      CollectionDropRate: '1',
      EnemyDropItemRate: '1',
      PlayerStomachDecreaceRate: '1.2',
      PalStomachDecreaceRate: '1.2',
      PlayerDamageRateDefense: '1.3',
      PalEggDefaultHatchingTime: '72',
      BuildObjectDeteriorationDamageRate: '1',
      DeathPenalty: 'All'
    }
  }
]

function CrossplayEditor({ value, onChange }: { value: string; onChange: (v: string) => void }): React.JSX.Element {
  const active = new Set(
    value
      .replace(/[()]/g, '')
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
  )
  const toggle = (platform: string, on: boolean): void => {
    const next = new Set(active)
    if (on) next.add(platform)
    else next.delete(platform)
    onChange(`(${CROSSPLAY_PLATFORMS.filter((p) => next.has(p)).join(',')})`)
  }
  return (
    <div className="row" style={{ gap: 14, flexWrap: 'wrap' }}>
      {CROSSPLAY_PLATFORMS.map((p) => (
        <label key={p} className="checkbox-row" style={{ margin: 0 }}>
          <input type="checkbox" checked={active.has(p)} onChange={(e) => toggle(p, e.target.checked)} />
          <span>{p}</span>
        </label>
      ))}
    </div>
  )
}

/** Full Palworld settings: curated essentials + every other OptionSettings key, grouped and searchable. */
export default function PalworldSettingsTab({ server }: { server: LocalServer }): React.JSX.Element {
  const toast = useToast()
  const [props, setProps] = useState<Record<string, string> | null>(null)
  const [dirty, setDirty] = useState<Record<string, string>>({})
  const [saving, setSaving] = useState(false)
  const [community, setCommunity] = useState(Boolean(server.communityServer))
  const [query, setQuery] = useState('')

  useEffect(() => {
    setDirty({})
    setQuery('')
    setCommunity(Boolean(server.communityServer))
    window.elauncher.server.getProperties(server.id).then(setProps).catch(console.error)
  }, [server.id, server.communityServer])

  const toggleCommunity = async (enabled: boolean): Promise<void> => {
    setCommunity(enabled)
    try {
      await window.elauncher.server.setCommunity(server.id, enabled)
      toast.success(enabled ? 'Community listing on — applies next time the server starts' : 'Community listing off')
    } catch (e) {
      setCommunity(!enabled)
      toast.error(e instanceof Error ? e.message : 'Could not update the community listing')
    }
  }

  const merged = useMemo(() => ({ ...(props ?? {}), ...dirty }), [props, dirty])
  const get = (key: string, fallback: string): string => merged[key] ?? fallback
  const set = (key: string, value: string): void => setDirty((d) => ({ ...d, [key]: value }))

  const save = async (): Promise<void> => {
    setSaving(true)
    try {
      const next = await window.elauncher.server.setProperties(server.id, dirty)
      setProps(next)
      setDirty({})
      toast.success('Saved — applies next time the server starts')
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Could not save settings')
    } finally {
      setSaving(false)
    }
  }

  /** Advanced keys grouped, filtered by the search box. */
  const groups = useMemo(() => {
    const q = query.trim().toLowerCase()
    const byGroup = new Map<string, string[]>()
    for (const key of Object.keys(merged)) {
      if (ESSENTIAL_KEYS.has(key)) continue
      const haystack = `${key} ${labelFor(key)} ${PALWORLD_SETTING_HINTS[key] ?? ''}`.toLowerCase()
      if (q && !haystack.includes(q)) continue
      const title = groupOf(key)
      byGroup.set(title, [...(byGroup.get(title) ?? []), key])
    }
    const order = [...GROUPS.map((g) => g.title), 'Other']
    return order
      .filter((t) => byGroup.has(t))
      .map((t) => ({ title: t, keys: (byGroup.get(t) ?? []).sort((a, b) => a.localeCompare(b)) }))
  }, [merged, query])

  if (!props) return <div className="skeleton" style={{ height: 180 }} />

  const num = (key: string, fallback: string, min: number, max: number, step = 1): React.JSX.Element => (
    <input type="number" min={min} max={max} step={step} value={get(key, fallback)} onChange={(e) => set(key, e.target.value)} />
  )

  const editor = (key: string): React.JSX.Element => {
    const value = get(key, '')
    const locked = key in LOCKED_KEYS
    const hint = PALWORLD_SETTING_HINTS[key]
    if (locked) {
      return (
        <div className="field" key={key}>
          <label>{labelFor(key)}</label>
          <input value={key === 'AdminPassword' ? '••••••••' : value} disabled />
          <div className="hint">{LOCKED_KEYS[key]}</div>
        </div>
      )
    }
    if (isBool(value)) {
      return (
        <label className="checkbox-row" key={key} style={{ alignSelf: 'end' }}>
          <input
            type="checkbox"
            checked={/^True$/i.test(value)}
            onChange={(e) => set(key, e.target.checked ? 'True' : 'False')}
          />
          <span>
            {labelFor(key)}
            {hint && <span className="faint small"> — {hint}</span>}
          </span>
        </label>
      )
    }
    let control: React.JSX.Element
    if (key === 'CrossplayPlatforms') {
      control = <CrossplayEditor value={value} onChange={(v) => set(key, v)} />
    } else if (key in ENUM_OPTIONS) {
      control = <Select value={value} onChange={(v) => set(key, v)} options={ENUM_OPTIONS[key]} />
    } else if (isNumeric(value) && /Rate$/.test(key)) {
      control = <RateEditor value={value} onChange={(v) => set(key, v)} />
    } else if (isNumeric(value)) {
      control = (
        <input
          type="number"
          step={value.includes('.') ? 0.1 : 1}
          value={trimFloat(value)}
          onChange={(e) => set(key, e.target.value)}
        />
      )
    } else {
      control = <input value={value} onChange={(e) => set(key, e.target.value)} />
    }
    return (
      <div className="field" key={key}>
        <label>{labelFor(key)}</label>
        {control}
        {hint && <div className="hint">{hint}</div>}
      </div>
    )
  }

  const dirtyCount = Object.keys(dirty).length

  const activePreset = SERVER_PRESETS.find((preset) =>
    Object.entries(preset.values).every(([key, wanted]) => {
      const current = merged[key]
      if (current === undefined) return false
      return isNumeric(wanted) && isNumeric(current)
        ? Math.abs(Number(current) - Number(wanted)) < 0.0001
        : current === wanted
    })
  )?.id

  const applyPreset = (id: string): void => {
    const preset = SERVER_PRESETS.find((p) => p.id === id)
    if (!preset) return
    setDirty((d) => ({ ...d, ...preset.values }))
    toast.success(`${preset.label} preset applied — review below, then Save`)
  }

  return (
    <>
      <div className="card settings-section">
        <div className="section-title">
          <span className="row" style={{ gap: 9 }}>
            <IconServer size={15} /> Essentials
          </span>
        </div>
        <div className="field">
          <label>Preset</label>
          <div className="segmented">
            {SERVER_PRESETS.map((preset) => (
              <button
                key={preset.id}
                className={activePreset === preset.id ? 'active' : ''}
                title={preset.blurb}
                onClick={() => applyPreset(preset.id)}
              >
                {preset.label}
              </button>
            ))}
          </div>
          <div className="hint">
            {SERVER_PRESETS.find((p) => p.id === activePreset)?.blurb ??
              'Custom — presets fill the key rates below; everything stays editable before you save.'}
          </div>
        </div>
        <div className="field">
          <label>Server name (shown on the join screen)</label>
          <input value={get('ServerName', server.name)} onChange={(e) => set('ServerName', e.target.value)} />
        </div>
        <div className="field">
          <label>Description</label>
          <input value={get('ServerDescription', '')} onChange={(e) => set('ServerDescription', e.target.value)} />
        </div>
        <div className="props-grid">
          <div className="field">
            <label>Join password (empty = open)</label>
            <input value={get('ServerPassword', '')} onChange={(e) => set('ServerPassword', e.target.value)} />
          </div>
          <div className="field">
            <label>Max players</label>
            {num('ServerPlayerMaxNum', '16', 1, 32)}
          </div>
          <div className="field">
            <label>XP rate</label>
            <RateEditor value={get('ExpRate', '1')} onChange={(v) => set('ExpRate', v)} />
          </div>
          <div className="field">
            <label>Pal capture rate</label>
            <RateEditor value={get('PalCaptureRate', '1')} onChange={(v) => set('PalCaptureRate', v)} />
          </div>
          <div className="field">
            <label>Day speed</label>
            <RateEditor value={get('DayTimeSpeedRate', '1')} onChange={(v) => set('DayTimeSpeedRate', v)} />
          </div>
          <div className="field">
            <label>Night speed</label>
            <RateEditor value={get('NightTimeSpeedRate', '1')} onChange={(v) => set('NightTimeSpeedRate', v)} />
          </div>
        </div>
        <div className="field">
          <label>Death penalty</label>
          <Select value={get('DeathPenalty', 'All')} onChange={(v) => set('DeathPenalty', v)} options={ENUM_OPTIONS.DeathPenalty} />
        </div>
        <label className="checkbox-row">
          <input type="checkbox" checked={community} onChange={(e) => void toggleCommunity(e.target.checked)} />
          <span>
            List in Palworld&apos;s community server browser{' '}
            <span className="faint small">— applies next start; needs UDP {server.port} reachable from the internet</span>
          </span>
        </label>
      </div>

      <div className="card settings-section">
        <div className="section-title">
          <span className="row" style={{ gap: 9 }}>
            <IconSliders size={15} /> All settings
          </span>
        </div>
        <div className="search-wrap">
          <IconSearch size={14} />
          <input placeholder="Search settings… (e.g. guild, drop, raid)" value={query} onChange={(e) => setQuery(e.target.value)} />
        </div>
        <div className="hint" style={{ marginTop: 6 }}>
          × settings are multipliers: 1 is the game&apos;s normal, 0.5 halves it, 2 doubles it.
        </div>
        {groups.length === 0 && <div className="hint">No settings match that search.</div>}
        {groups.map((group) => (
          <div key={group.title}>
            <div
              className="small faint"
              style={{ fontWeight: 650, textTransform: 'uppercase', letterSpacing: '.4px', margin: '12px 0 6px' }}
            >
              {group.title}
            </div>
            <div className="props-grid">{group.keys.map((key) => editor(key))}</div>
          </div>
        ))}
        <div className="hint" style={{ marginTop: 10 }}>
          Values map 1:1 to PalWorldSettings.ini — unknown keys are preserved, and changes apply on the next server start.
        </div>
      </div>

      {dirtyCount > 0 && (
        <div
          className="card"
          style={{ position: 'sticky', bottom: 12, zIndex: 5, display: 'flex', alignItems: 'center', gap: 12, padding: '10px 14px' }}
        >
          <button className="primary" disabled={saving} onClick={() => void save()}>
            {saving ? 'Saving…' : `Save ${dirtyCount} ${dirtyCount === 1 ? 'change' : 'changes'}`}
          </button>
          <span className="small faint">restart the server to apply</span>
          <button className="ghost small" style={{ marginLeft: 'auto' }} disabled={saving} onClick={() => setDirty({})}>
            Discard
          </button>
        </div>
      )}
    </>
  )
}
