/**
 * Plain-English explanations for PalWorldSettings.ini keys, shown under each
 * field in the settings tab and searched alongside key names. Keys the server
 * adds in future patches simply render without a hint.
 */
export const PALWORLD_SETTING_HINTS: Record<string, string> = {
  // world & time
  Difficulty: 'Overall difficulty preset. None means the individual sliders below are used.',
  RandomizerType: 'Shuffles which Pals spawn where — Region shuffles by area, All is fully random.',
  RandomizerSeed: 'Seed for the Pal randomizer; the same seed gives the same shuffle.',
  bIsRandomizerPalLevelRandom: 'Randomized Pals also spawn with random levels.',
  DayTimeSpeedRate: 'How fast daytime passes (2 = days fly by twice as fast).',
  NightTimeSpeedRate: 'How fast nighttime passes.',
  ExpRate: 'XP multiplier for players and Pals.',
  WorkSpeedRate: 'Work speed multiplier for Pals at your bases.',
  SupplyDropSpan: 'Minutes between supply-drop events.',

  // pals
  PalCaptureRate: 'Capture chance multiplier when throwing Pal Spheres.',
  PalSpawnNumRate: 'How many wild Pals spawn — higher means more Pals but more server load.',
  PalDamageRateAttack: 'Damage dealt by Pals.',
  PalDamageRateDefense: 'Damage taken by Pals — higher makes Pals squishier.',
  PalStomachDecreaceRate: 'How fast Pals get hungry.',
  PalStaminaDecreaceRate: 'How fast Pals tire out.',
  PalAutoHPRegeneRate: 'Passive HP regeneration for Pals.',
  PalAutoHpRegeneRateInSleep: 'Pal HP regeneration while sleeping (or stored in the Palbox).',
  PalEggDefaultHatchingTime: 'Hours for the largest eggs to hatch; smaller eggs scale down from this.',
  bPalLost: 'Hardcore for Pals — a Pal that faints with its owner is lost forever.',

  // players & combat
  PlayerDamageRateAttack: 'Damage dealt by players.',
  PlayerDamageRateDefense: 'Damage taken by players — higher means you take more.',
  PlayerStomachDecreaceRate: 'How fast players get hungry.',
  PlayerStaminaDecreaceRate: 'How fast player stamina drains.',
  PlayerAutoHPRegeneRate: 'Passive HP regeneration for players.',
  PlayerAutoHpRegeneRateInSleep: 'Player HP regeneration while sleeping.',
  bEnablePlayerToPlayerDamage: 'Players can hurt each other directly, even outside PvP.',
  bEnableFriendlyFire: 'Attacks damage your own guildmates and Pals too.',
  bEnableInvaderEnemy: 'Raid events — hostile groups periodically attack your base.',
  bEnableAimAssistPad: 'Aim assist for controller players.',
  bEnableAimAssistKeyboard: 'Aim assist for mouse and keyboard players.',
  bIsPvP: 'Enables PvP between players.',
  bHardcore: 'Hardcore mode — dying has permanent consequences.',
  bCharacterRecreateInHardcore: 'Allow making a new character after a hardcore death.',
  DeathPenalty: 'What you drop when you die.',
  bActiveUNKO: 'Enables the poop joke item. Yes, really.',

  // items & drops
  ItemWeightRate: 'Item weight multiplier — 0 makes everything weightless.',
  EquipmentDurabilityDamageRate: 'How fast weapons and armor lose durability.',
  CollectionDropRate: 'Resource yield from trees, ore, and other gatherables.',
  CollectionObjectHpRate: 'Toughness of gatherable nodes — higher takes more hits.',
  CollectionObjectRespawnSpeedRate: 'Respawn interval for gatherables — higher means slower respawns.',
  EnemyDropItemRate: 'Loot dropped by defeated enemies.',
  DropItemMaxNum: 'Maximum items lying on the ground before the oldest despawn.',
  DropItemMaxNum_UNKO: 'Maximum dropped poop items. A setting that exists.',
  DropItemAliveMaxHours: 'Hours before dropped items despawn.',
  bCanPickupOtherGuildDeathPenaltyDrop: "Players can loot other guilds' death drops.",

  // base camps & guilds
  BaseCampMaxNum: 'Maximum base camps across the entire server.',
  BaseCampWorkerMaxNum: 'Maximum Pals working at one base.',
  BuildObjectDamageRate: 'Damage dealt to buildings.',
  BuildObjectDeteriorationDamageRate: 'How fast unattended buildings decay — 0 disables decay.',
  MaxBuildingLimitNum: 'Maximum structures per player — 0 means unlimited.',
  bEnableDefenseOtherGuildPlayer: 'Base defenses also target players from other guilds.',
  bInvisibleOtherGuildBaseCampAreaFX: "Hides other guilds' base-area boundary effects.",
  GuildPlayerMaxNum: 'Maximum members per guild.',
  bAutoResetGuildNoOnlinePlayers: 'Automatically disband guilds whose members stop logging in.',
  AutoResetGuildTimeNoOnlinePlayers: 'Hours of guild inactivity before that auto-reset happens.',

  // multiplayer & access
  ServerPlayerMaxNum: 'Maximum players connected at once.',
  CoopPlayerMaxNum: 'Player cap for invite-code co-op sessions — not used by dedicated servers.',
  bIsMultiplay: 'Co-op session flag — leave off for dedicated servers.',
  bEnableNonLoginPenalty: 'Apply decay (hunger etc.) to players who stay logged out.',
  bEnableFastTravel: 'Fast travel between unlocked statues.',
  bIsStartLocationSelectByMap: 'New players choose their spawn point on the map.',
  bExistPlayerAfterLogout: 'Player bodies remain in the world after logging out.',
  ChatPostLimitPerMinute: 'Maximum chat messages per player per minute.',
  bAllowClientMod: 'Allow players running client-side mods to join.',
  bShowPlayerList: 'Show the online player list on the pause screen.',

  // saves & maintenance
  bIsUseBackupSaveData: "Palworld's own rolling save backups (separate from ELauncher's backups).",
  LogFormatType: 'Format of the server log output.',
  ItemContainerForceMarkDirtyInterval: 'Internal save-marking interval — leave at default.',
  ServerReplicatePawnCullDistance: "Distance at which other players' Pals are synced to you — higher sees further but uses more bandwidth.",

  // newer keys (recent Palworld updates)
  BuildObjectHpRate: 'Toughness of buildings — higher makes structures take more hits to destroy.',
  PhysicsActiveDropItemMaxNum: 'Maximum dropped items simulated with physics at once — lower helps performance.',
  BaseCampMaxNumInGuild: 'Maximum base camps a single guild can place.',
  AutoSaveSpan: "Seconds between the server's own world autosaves.",
  bEnableFastTravelOnlyBaseCamp: 'Restrict fast travel to base camps only — no map statues.',
  bBuildAreaLimit: 'Only allow building inside base camp areas.',
  bIsShowJoinLeftMessage: 'Announce player joins and leaves in chat.',
  EnablePredatorBossPal: 'Roaming predator boss Pals spawn in the world.',
  bAllowGlobalPalboxExport: 'Players may export Pals to the global Palbox (cross-server transfer).',
  bAllowGlobalPalboxImport: 'Players may import Pals from the global Palbox — off keeps progression local to this server.',
  ItemCorruptionMultiplier: 'How fast food and other perishables spoil.',
  MonsterFarmActionSpeedRate: 'Work speed of Pals assigned to the Ranch.',
  DenyTechnologyList: 'Comma-separated technology IDs players are not allowed to unlock.',
  GuildRejoinCooldownMinutes: 'Minutes a player must wait before rejoining a guild after leaving.',
  AutoTransferMasterCheckIntervalSeconds: 'How often the server checks for an inactive guild master (seconds).',
  AutoTransferMasterThresholdDays: 'Days of guild-master inactivity before leadership auto-transfers to an active member.',
  MaxGuildsPerFrame: 'Internal guild-processing budget per frame — leave at default.',
  BlockRespawnTime: 'Seconds respawning stays blocked after death.',
  RespawnPenaltyDurationThreshold: 'Dying repeatedly within this window triggers the respawn penalty.',
  RespawnPenaltyTimeScale: 'How much the respawn wait grows while the penalty is active.',
  'bDisplayPvPItemNumOnWorldMap_BaseCamp': 'PvP: show counts of dropped loot at base camps on the world map.',
  'bDisplayPvPItemNumOnWorldMap_Player': 'PvP: show counts of dropped loot on players on the world map.',
  bAdditionalDropItemWhenPlayerKillingInPvPMode: 'PvP: killing a player drops an extra bounty item.',
  AdditionalDropItemWhenPlayerKillingInPvPMode: 'PvP: which extra item drops on a player kill.',
  AdditionalDropItemNumWhenPlayerKillingInPvPMode: 'PvP: how many of that extra item drop.',
  bEnableVoiceChat: 'Built-in proximity voice chat.',
  VoiceChatMaxVolumeDistance: 'Distance where voices are still at full volume.',
  VoiceChatZeroVolumeDistance: 'Distance where voices fade to silence.',
  'bAllowEnhanceStat_Health': 'Allow players to enhance the Health stat.',
  'bAllowEnhanceStat_Attack': 'Allow players to enhance the Attack stat.',
  'bAllowEnhanceStat_Stamina': 'Allow players to enhance the Stamina stat.',
  'bAllowEnhanceStat_Weight': 'Allow players to enhance carry Weight.',
  'bAllowEnhanceStat_WorkSpeed': 'Allow players to enhance Work Speed.',
  bEnableBuildingPlayerUIdDisplay: "Show the builder's player ID on structures — handy for moderating public servers.",
  BuildingNameDisplayCacheTTLSeconds: 'Cache lifetime for building name labels (seconds) — leave at default.',

  // network & platform
  PublicPort: 'The UDP port announced publicly. ELauncher keeps this in sync with the server.',
  Region: 'Region tag shown in the community server browser.',
  bUseAuth: 'Verify player accounts on join — keep this on.',
  BanListURL: "URL of the ban list the server enforces (Pocketpair's official list by default).",
  RCONEnabled: 'Legacy RCON admin protocol — ELauncher manages the server over the REST API instead.',
  RCONPort: 'Port for RCON, when enabled.',
  CrossplayPlatforms: 'Which platforms are allowed to join together.'
}
