-- ELauncher migration — invite links and the application system.
-- Idempotent: safe to run more than once. Paste into Supabase → SQL Editor → Run.
--
-- An invite link is a short code someone can hand out. Opening it shows a public
-- card for the server; joining a private or whitelisted one means signing in and
-- answering questions the owner wrote, which the owner then approves or denies.
--
-- Security shape, deliberately: anonymous visitors get **no table access at all**.
-- They call one security-definer function that returns exactly the fields an
-- invite card needs. A table policy would have exposed owner_id, every other
-- invite's row shape, and whatever columns get added here later.

-- ============================================================
-- invite links
-- ============================================================
create table if not exists public.server_invites (
  -- short and URL-safe; generated by the launcher, not a uuid, because this
  -- ends up in a link people type and read out loud
  code text primary key,
  server_id uuid not null,
  owner_id uuid not null references public.profiles (id) on delete cascade,
  -- denormalised so the invite card renders without touching the servers table,
  -- which anonymous callers must never reach
  server_name text not null default '',
  game text not null default 'minecraft',
  headline text not null default '',
  description text not null default '',
  /*
   * Owner-defined application form, as
   *   [{ "id": "ign", "label": "Your in-game name", "type": "text", "required": true }]
   * type is text | textarea | select, with "options" for select. An empty array
   * means the link needs no application: sign in and you are through.
   */
  questions jsonb not null default '[]',
  -- what an approved applicant is told: a Discord invite, join instructions, whatever
  approval_message text not null default '',
  enabled boolean not null default true,
  expires_at timestamptz,
  -- null = unlimited
  max_uses integer,
  uses integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists server_invites_owner_idx on public.server_invites (owner_id);
create index if not exists server_invites_server_idx on public.server_invites (server_id);

alter table public.server_invites enable row level security;

-- owners manage their own links; admins see the lot. No anon policy on purpose.
drop policy if exists "owners manage their invites" on public.server_invites;
create policy "owners manage their invites"
  on public.server_invites for all to authenticated
  using (owner_id = auth.uid() or public.is_admin())
  with check (owner_id = auth.uid() or public.is_admin());

-- ============================================================
-- applications
-- ============================================================
create table if not exists public.server_applications (
  id uuid primary key default gen_random_uuid(),
  code text not null references public.server_invites (code) on delete cascade,
  server_id uuid not null,
  owner_id uuid not null references public.profiles (id) on delete cascade,
  applicant_id uuid not null references public.profiles (id) on delete cascade,
  -- captured at submit time so a decision email still works if the profile changes
  applicant_email text not null default '',
  applicant_name text not null default '',
  answers jsonb not null default '{}',
  status text not null default 'pending' check (status in ('pending', 'approved', 'denied')),
  owner_note text not null default '',
  decided_at timestamptz,
  decided_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  -- one application per person per link; re-applying updates rather than piles up
  unique (code, applicant_id)
);

create index if not exists server_applications_owner_idx on public.server_applications (owner_id, status);
create index if not exists server_applications_applicant_idx on public.server_applications (applicant_id);

alter table public.server_applications enable row level security;

-- an applicant reads their own; the owner reads and decides on theirs
drop policy if exists "applicants read their own applications" on public.server_applications;
create policy "applicants read their own applications"
  on public.server_applications for select to authenticated
  using (applicant_id = auth.uid() or owner_id = auth.uid() or public.is_admin());

drop policy if exists "owners decide on applications" on public.server_applications;
create policy "owners decide on applications"
  on public.server_applications for update to authenticated
  using (owner_id = auth.uid() or public.is_admin())
  with check (owner_id = auth.uid() or public.is_admin());

-- inserts go through apply_to_invite() so the link's own rules are enforced;
-- no direct insert policy exists, which is what stops a closed link being used
drop policy if exists "owners remove applications" on public.server_applications;
create policy "owners remove applications"
  on public.server_applications for delete to authenticated
  using (owner_id = auth.uid() or public.is_admin());

-- ============================================================
-- what an anonymous visitor may see
-- ============================================================
/*
 * Everything the invite card needs and nothing else. Note what is absent:
 * owner_id, server_id, the join address, and any hint about other servers.
 * The address is deliberately withheld until an application is approved — a
 * public link that leaked the address would make whitelisting the only thing
 * standing between a stranger and the server.
 */
create or replace function public.invite_view(invite_code text)
returns jsonb
language plpgsql
security definer set search_path = public
stable
as $$
declare
  inv public.server_invites%rowtype;
  st public.server_status%rowtype;
  closed text := null;
begin
  select * into inv from public.server_invites where code = invite_code;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'unknown');
  end if;

  if not inv.enabled then closed := 'disabled';
  elsif inv.expires_at is not null and inv.expires_at < now() then closed := 'expired';
  elsif inv.max_uses is not null and inv.uses >= inv.max_uses then closed := 'full';
  end if;

  select * into st from public.server_status where server_id = inv.server_id;

  return jsonb_build_object(
    'ok', true,
    'code', inv.code,
    'serverName', inv.server_name,
    'game', inv.game,
    'headline', inv.headline,
    'description', inv.description,
    'questions', inv.questions,
    'needsApplication', jsonb_array_length(inv.questions) > 0,
    'closed', closed,
    -- live status is best-effort: a host that has never checked in simply has none
    'state', coalesce(st.state, 'unknown'),
    'players', coalesce(st.players_online, 0)
  );
end;
$$;

grant execute on function public.invite_view(text) to anon, authenticated;

-- ============================================================
-- applying
-- ============================================================
/*
 * Submitting an application. A function rather than an insert policy because the
 * link's rules — enabled, not expired, not full — have to be checked at the
 * moment of writing. Re-applying to the same link updates the existing row, so a
 * decided application cannot be silently replaced by a fresh pending one.
 */
create or replace function public.apply_to_invite(invite_code text, submitted jsonb)
returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  inv public.server_invites%rowtype;
  me uuid := auth.uid();
  my_email text;
  my_name text;
  existing public.server_applications%rowtype;
begin
  if me is null then
    return jsonb_build_object('ok', false, 'reason', 'not signed in');
  end if;

  select * into inv from public.server_invites where code = invite_code;
  if not found then return jsonb_build_object('ok', false, 'reason', 'unknown'); end if;
  if not inv.enabled then return jsonb_build_object('ok', false, 'reason', 'disabled'); end if;
  if inv.expires_at is not null and inv.expires_at < now() then
    return jsonb_build_object('ok', false, 'reason', 'expired');
  end if;
  if inv.max_uses is not null and inv.uses >= inv.max_uses then
    return jsonb_build_object('ok', false, 'reason', 'full');
  end if;

  select p.username into my_name from public.profiles p where p.id = me;
  select u.email into my_email from auth.users u where u.id = me;

  select * into existing from public.server_applications where code = invite_code and applicant_id = me;
  if found then
    -- an approved applicant re-opening the link is already in; say so rather
    -- than resetting them to pending
    if existing.status = 'approved' then
      return jsonb_build_object('ok', true, 'status', 'approved', 'already', true);
    end if;
    update public.server_applications
      set answers = submitted, status = 'pending', owner_note = '', decided_at = null, decided_by = null,
          applicant_email = coalesce(my_email, ''), applicant_name = coalesce(my_name, '')
      where id = existing.id;
    return jsonb_build_object('ok', true, 'status', 'pending', 'id', existing.id, 'already', false);
  end if;

  insert into public.server_applications (code, server_id, owner_id, applicant_id, applicant_email, applicant_name, answers)
  values (invite_code, inv.server_id, inv.owner_id, me, coalesce(my_email, ''), coalesce(my_name, ''), submitted)
  returning * into existing;

  update public.server_invites set uses = uses + 1 where code = invite_code;
  return jsonb_build_object('ok', true, 'status', 'pending', 'id', existing.id, 'already', false);
end;
$$;

grant execute on function public.apply_to_invite(text, jsonb) to authenticated;

-- ============================================================
-- deciding
-- ============================================================
/*
 * Approve or deny. Returns the applicant's email and the owner's approval
 * message so the caller can send the decision mail without a second round trip
 * (and without the panel needing read access to auth.users).
 */
create or replace function public.decide_application(application_id uuid, approve boolean, note text default '')
returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  app public.server_applications%rowtype;
  inv public.server_invites%rowtype;
begin
  select * into app from public.server_applications where id = application_id;
  if not found then return jsonb_build_object('ok', false, 'reason', 'unknown'); end if;
  if app.owner_id <> auth.uid() and not public.is_admin() then
    raise exception 'not authorised';
  end if;

  update public.server_applications
    set status = case when approve then 'approved' else 'denied' end,
        owner_note = coalesce(note, ''),
        decided_at = now(),
        decided_by = auth.uid()
    where id = application_id
    returning * into app;

  select * into inv from public.server_invites where code = app.code;

  return jsonb_build_object(
    'ok', true,
    'status', app.status,
    'email', app.applicant_email,
    'name', app.applicant_name,
    'serverName', coalesce(inv.server_name, ''),
    -- only an approval carries the join instructions
    'message', case when approve then coalesce(inv.approval_message, '') else coalesce(note, '') end
  );
end;
$$;

grant execute on function public.decide_application(uuid, boolean, text) to authenticated;

-- make PostgREST pick the new tables and functions up immediately
notify pgrst, 'reload schema';
